steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'dataflow'
      - 'jobs'
      - 'cancel'
      - 'iot'
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - 'cp'
      - ''
      - 'gs://de-porto/dataflow-jobs/'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'dataflow'
      - 'jobs'
      - 'run'
      - 'iot'