steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'dataflow'
      - 'jobs'
      - 'cancel'
      - 'iot'
      - '--region'
      - 'asia-southeast2'
  - name: python:3.8.12-bullseye
    entrypoint: pip
    args: ["install", "-r", "src/dataflow/requirement.txt", "--user"]
  - name: python:3.8.12-bullseye
    entrypoint: python
    args:
      - 'src/dataflow/iot-pipeline.py'
      - '--runner'
      - 'DataflowRunner'
      - '--project'
      - 'de-porto'
      - '--temp_location'
      - 'gs://de-porto/temp'
      - '--staging_location'
      - 'gs://de-porto/staging'
      - '--template_location'
      - 'gs://de-porto/dataflow-template/iot-pipeline'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'dataflow'
      - 'jobs'
      - 'run'
      - 'iot'
      - '--gcs-location'
      - 'gs://de-porto/dataflow-template/iot-pipeline'
      - '--enable-streaming-engine'
      - '--max-workers'
      - '1'
      - '--num-workers'
      - '1'
      - '--worker-machine-type'
      - 'n1-standard-1'
      - '--region'
      - 'asia-southeast2'

options:
  logging: CLOUD_LOGGING_ONLY