steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'dataflow'
      - 'jobs'
      - 'cancel'
      - 'iot'
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - 'cp'
      - 'src/dataflow/iot-pipeline.py'
      - 'gs://de-porto/dataflow-jobs/'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'dataflow'
      - 'jobs'
      - 'run'
      - 'iot'
      - '--gcs-location'
      - 'gs://de-porto/dataflow-jobs/iot-pipeline.py'
      - '--enable-streaming-engine'
      - '--max-workers'
      - '1'
      - '--num-workers'
      - '1'
      - '--worker-machine-type'
      - 'n1-standard-1'
      - '--region'
      - 'asia-southeast2'

options:
  logging: CLOUD_LOGGING_ONLY